// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

#define n 32

extern "C" {
void gemv_mm2s_scalar(int alpha, int beta,
                      hls::stream<qdma_axis<32, 0, 0, 0>> &stream_alpha,
                      hls::stream<qdma_axis<32, 0, 0, 0>> &stream_beta) {
#pragma HLS interface axis port = stream_alpha
#pragma HLS interface axis port = stream_beta
#pragma HLS INTERFACE s_axilite port = alpha bundle = control
#pragma HLS INTERFACE s_axilite port = beta bundle = control
#pragma HLS interface s_axilite port = return bundle = control

    qdma_axis<32,0,0,0> scalar_alpha;
    scalar_alpha.data = alpha;
    scalar_alpha.keep_all();
    scalar_alpha.set_last(1);
    stream_alpha.write(scalar_alpha);

    qdma_axis<32,0,0,0> scalar_beta;
    scalar_beta.data = beta;
    scalar_beta.keep_all();
    scalar_beta.set_last(1);
    stream_beta.write(scalar_beta);
}
}
