// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

extern "C" {
void gemv_mm2s_y(ap_int<32> *mem_y, int m,
                 hls::stream<qdma_axis<32, 0, 0, 0>> &stream_y) {
#pragma HLS interface m_axi port = mem_y offset = slave
#pragma HLS interface axis port = stream_y
#pragma HLS INTERFACE s_axilite port = mem_y bundle = control
#pragma HLS INTERFACE s_axilite port = m bundle = control
#pragma HLS interface s_axilite port = return bundle = control

    // Send data over stream
    for (int i = 0; i < m; i++) {
        #pragma HLS pipeline II = 1
        qdma_axis<32,0,0,0> y;
        y.data = mem_y[i];
        y.keep_all();
        stream_y.write(y);
    }
}
}
