// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

extern "C" {
void gemv_s2mm(ap_int<32> *mem, int m,
               hls::stream<qdma_axis<32, 0, 0, 0>> &stream_out) {
#pragma HLS interface m_axi port = mem offset = slave
#pragma HLS interface axis port = stream_out

#pragma HLS INTERFACE s_axilite port = mem bundle = control
#pragma HLS INTERFACE s_axilite port = m bundle = control
#pragma HLS interface s_axilite port = return bundle = control

    // Send data over stream
    for (int i = 0; i < m; i++) {
        #pragma HLS pipeline II = 1
        qdma_axis<32, 0, 0, 0> out = stream_out.read();
        mem[i] = out.data;
    }
}
}
