// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

#define n 64

extern "C" {
void gemv_mm2s_x(ap_int<32> *mem_x,
                 hls::stream<qdma_axis<32, 0, 0, 0>> &stream_x) {
#pragma HLS interface m_axi port = mem_x offset = slave
#pragma HLS interface axis port = stream_x
#pragma HLS INTERFACE s_axilite port = mem_x bundle = control
#pragma HLS interface s_axilite port = return bundle = control
    for (int j = 0; j < n; j++) {
        #pragma HLS unroll
        qdma_axis<32,0,0,0> x;
        x.data = mem_x[j];
        x.keep_all();
        stream_x.write(x);
    }
}
}
