// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

#define n 64

extern "C" {
void gemv_mm2s_A(ap_int<32> *mem_A, int m,
                 hls::stream<qdma_axis<32, 0, 0, 0>> &stream_A) {
#pragma HLS interface m_axi port = mem_A offset = slave
#pragma HLS interface axis port = stream_A
#pragma HLS INTERFACE s_axilite port = mem_A bundle = control
#pragma HLS INTERFACE s_axilite port = m bundle = control
#pragma HLS interface s_axilite port = return bundle = control

    // Send data over stream
    for (int i = 0; i < m; i++) {
        #pragma HLS pipeline II = n
        for (int j = 0; j < n; j++) {
            #pragma HLS unroll
            qdma_axis<32,0,0,0> A;
            A.data = mem_A[i * n + j];
            A.keep_all();
            stream_A.write(A);
        }
    }
}
}
