// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include "graph.hpp"

simpleGraph mygraph;

int main (void) {
    adf::return_code ret;
    mygraph.init();

    ret = mygraph.run(1);
    if (ret != adf::ok) {
        printf("Run failed\n");
        return ret;
    }

    ret = mygraph.end();
    if (ret != adf::ok) {
        printf("End failed\n");
        return ret;
    }

    return 0;
}
