// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <adf.h>
#include "kernels/gemv.hpp"

using namespace adf;

class simpleGraph : public graph {
private:
    kernel gemvk;

public:
    input_plio gemv_alpha;
    input_plio gemv_A;
    input_plio gemv_x;
    input_plio gemv_beta;
    input_plio gemv_y;
    output_plio gemv_out;

    simpleGraph() {
        // initialize gemv
        gemv_alpha = input_plio::create("gemv_alpha", plio_32_bits, "data/gemv_alpha.txt");
        gemv_A = input_plio::create("gemv_A", plio_32_bits, "data/gemv_A.txt");
        gemv_x = input_plio::create("gemv_x", plio_32_bits, "data/gemv_x.txt");
        gemv_beta = input_plio::create("gemv_beta", plio_32_bits, "data/gemv_beta.txt");
        gemv_y = input_plio::create("gemv_y", plio_32_bits, "data/gemv_y.txt");
        gemv_out = output_plio::create("gemv_out", plio_32_bits, "data/gemv_out.txt");

        gemvk = kernel::create(gemv);

        // connect gemv
        connect<stream> net0(gemv_alpha.out[0], gemvk.in[0]);
        connect<window<256>> net1(gemv_A.out[0], gemvk.in[1]);
        connect<window<256>> net2(gemv_x.out[0], async(gemvk.in[2]));
        connect<stream> net3(gemv_beta.out[0], gemvk.in[3]);
        connect<window<256>> net4(gemv_y.out[0], async(gemvk.in[4]));
        connect<window<256>> net5(async(gemvk.out[0]), gemv_out.in[0]);

        source(gemvk) = "kernels/gemv.cpp";
        runtime<ratio>(gemvk) = 0.9;

    }
};
