// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

#define Tm 64

extern "C" {
void gemv_mm2s_x(ap_int<32> *mem_x, int m, int n,
                 hls::stream<qdma_axis<32, 0, 0, 0>> &stream_x) {
#pragma HLS interface m_axi port = mem_x offset = slave
#pragma HLS interface axis port = stream_x
#pragma HLS INTERFACE s_axilite port = mem_x bundle = control
#pragma HLS INTERFACE s_axilite port = m bundle = control
#pragma HLS INTERFACE s_axilite port = n bundle = control
#pragma HLS interface s_axilite port = return bundle = control
    unsigned repeat = n * (m / Tm);
    for (unsigned i = 0; i < repeat; ++i) {
        #pragma HLS pipeline II=1
        qdma_axis<32,0,0,0> x;
        x.data = mem_x[i % n];
        x.keep_all();
        stream_x.write(x);
    }
}
}
