// This file was auto-generated by aieblas on 2024-7-19 at 13:38

#include <ap_int.h>
#include <hls_stream.h>
#include <ap_axi_sdata.h>

extern "C" {
void gemv_mm2s_scalar(int n, int alpha, int beta,
                      hls::stream<qdma_axis<32, 0, 0, 0>> &stream_scalar) {
#pragma HLS interface axis port = stream_scalar
#pragma HLS INTERFACE s_axilite port = n bundle = control
#pragma HLS INTERFACE s_axilite port = alpha bundle = control
#pragma HLS INTERFACE s_axilite port = beta bundle = control
#pragma HLS interface s_axilite port = return bundle = control

    qdma_axis<32,0,0,0> scalar_n;
    scalar_n.data = n;
    scalar_n.keep_all();
    stream_scalar.write(scalar_n);

    qdma_axis<32,0,0,0> scalar_alpha;
    scalar_alpha.data = alpha;
    scalar_alpha.keep_all();
    stream_scalar.write(scalar_alpha);

    qdma_axis<32,0,0,0> scalar_beta;
    scalar_beta.data = beta;
    scalar_beta.keep_all();
    scalar_beta.set_last(1);
    stream_scalar.write(scalar_beta);
}
}
